### ISSUE TITLE
Index on arbitrary keys?

### ISSUE THREAD

**Issue by untoldone** [gorilla/context#19]
I currently have a helper that is used to render to a `http.ResponseWriter`. Currently, the renderer is built conditionally on parameters in the request in a middleware far away from the request handling code. The result is that I could have relatively clean handler code like this:

    func SearchHandler (w http.ResponseWriter, req *http.Request) {
      someResult := <do some stuff that doesn't ever fail>
      renderJSON(w, http.StatusOK, someResult)
    }

However, if I want to access the context created by the middleware, I also need to have `req` passed to `renderJSON` just to get the context.

If instead, I could key the context based on the `http.ResponseWriter`, I would be able to keep my signatures cleaner.

Perhaps there are other solutions here too that involve completely different patterns than I'm currently using.

**Comment by elithrar** [comment]
I'm going to close this one out due to inactivity but happy to re-open if there's still a desire to discuss.
