### ISSUE TITLE
request-oriented mutex

### ISSUE THREAD

**Issue by v2e4lisp** [gorilla/context#23]
I notice that there is only one mutex in the `context` package. I assume if some request call `context.Set` and therefore hold the write lock,  at that moment, any other request will have to wait for it while they don't need to, since the `context` is request-oriented and preventing race conditions between requests is not its concern. Would it be nice if we let each request have its own mutex.

```go
var (
	mutexes = make(map[http.Request]sync.RWMutex)
	data  = make(map[*http.Request]map[interface{}]interface{})
	datat = make(map[*http.Request]int64)
)
```

**Comment by kisielk** [comment]
If you can provide a benchmark that shows this is a problem and your approach would provide overall better performance, I'd consider making the change. Right now there's no evidence it's a problem.

**Comment by elithrar** [comment]
Hey @v2e4lisp — if you're still keen on producing some benchmarks I'd love to see them. From my experience however I'd expect the results to be very minor.

**Comment by elithrar** [comment]
I'm going to close this one out for now, but feel free to re-open. As above, my own benchmarks show little difference across different locking methods (and even different locks) - an spinlock lib written in asm still didn't show consistently better results than the status quo.
