### ISSUE TITLE
Wrong use of gorilla/context ?

### ISSUE THREAD

**Issue by Karthic-Hackintosh** [gorilla/context#25]
The website https://www.nicolasmerouze.com/share-values-between-middlewares-context-golang/ ,  defines the use of gorilla in the following manner ,
  
    func myHandler(w http.ResponseWriter, r *http.Request) {
          context.Set(r, "foo", "bar")
    }

    func myOtherHandler(w http.ResponseWriter, r *http.Request) {
      val := context.Get(r, "foo").(string)
    }
Is it possible to do a Set in one handler and then  Get in another handler to fetch back the former ?Its not possible right ?

**Comment by elithrar** [comment]
No: you can't set/get across different requests as *http.Request is the
implicit map key.

You can do it across handlers if they are chained - i.e. one is acting as
middleware, wrapping the other.

**Comment by Karthic-Hackintosh** [comment]
Yes , Thank you
