### ISSUE TITLE
Create annotated tags for releases

### ISSUE THREAD

**Issue by benma** [gorilla/context#29]
Hi

It would be great if you tagged the current HEAD with v1.0.0, and in the future, occasionally bump the version and make new tags with new releases. I suggest using the semver.org versioning scheme, where you have major.minor.patch, and you bump the major for incompatible changes and the minor for compatible changes to the API.

There are already tags in your other repo, https://github.com/gorilla/mux

**Comment by elithrar** [comment]
Sure. Thankfully I know how semver works, but as this library predates vendoring, it's also unlikely any breaking changes will happen under this repo.

**Comment by elithrar** [comment]
Done! Thanks for the reminder. https://github.com/gorilla/context/releases/tag/v1.1
